import {
  ActivityEditor,
  BottomBarEditor,
  CardsEditor,
  CodeEditor,
  DividerEditor,
  DownloadEditor,
  FaqEditor,
  FooterEditor,
  FormEditor,
  HeroEditor,
  ImageEditor,
  LinksEditor,
  MapEditor,
  ReservationEditor,
  ScheduleEditor,
  SearchEditor,
  SpacerEditor,
  TextEditor,
  TimerEditor,
  TopNavEditor,
  YouTubeEditor,
} from './blockEditorLazyImports.jsx';

export {
  ActivityEditor,
  BottomBarEditor,
  CardsEditor,
  CodeEditor,
  DividerEditor,
  DownloadEditor,
  FaqEditor,
  FooterEditor,
  FormEditor,
  HeroEditor,
  ImageEditor,
  LinksEditor,
  MapEditor,
  ReservationEditor,
  ScheduleEditor,
  SearchEditor,
  SpacerEditor,
  TextEditor,
  TimerEditor,
  TopNavEditor,
  YouTubeEditor,
} from './blockEditorLazyImports.jsx';

export const BLOCK_EDITORS = {
  topnav: TopNavEditor,
  hero: HeroEditor,
  image: ImageEditor,
  youtube: YouTubeEditor,
  text: TextEditor,
  cards: CardsEditor,
  map: MapEditor,
  faq: FaqEditor,
  links: LinksEditor,
  download: DownloadEditor,
  schedule: ScheduleEditor,
  timer: TimerEditor,
  activity: ActivityEditor,
  spacer: SpacerEditor,
  divider: DividerEditor,
  code: CodeEditor,
  search: SearchEditor,
  form: FormEditor,
  reservation: ReservationEditor,
  bottombar: BottomBarEditor,
  footer: FooterEditor,
};