export function generateStandaloneFormHtml(form){
  const safe = {
    title: form?.title || '상담 신청',
    desc: form?.desc || '',
    submit: form?.submit || '신청하기',
    successTitle: form?.successTitle || '상담 신청 완료',
    success: form?.success || '상담 신청이 접수되었습니다.',
    privacy: form?.privacy || '개인정보 수집 및 이용에 동의합니다.',
    privacyRequired: form?.privacyRequired ?? true,
    privacyDetail: form?.privacyDetail || '',
    questions: Array.isArray(form?.questions) ? form.questions : [],
  };
  const data = JSON.stringify(safe).replace(/</g,'\\u003c');
  return `<!-- Inlet Form Embed Start -->
<div id="inlet-form-root"></div>
<script>window.INLET_FORM_CONFIG=${data};window.INLET_WEBHOOK_URL=window.INLET_WEBHOOK_URL||'';</script>
<script>
(function(){
var cfg=window.INLET_FORM_CONFIG||{},root=document.getElementById('inlet-form-root'),brand='Inlet'; if(!root)return;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(s){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s];});}
function notice(msg){var box=root.querySelector('[data-inlet-notice]');if(!box){box=document.createElement('div');box.setAttribute('data-inlet-notice','true');box.style.cssText='margin:10px 0;padding:10px 12px;border-radius:12px;background:#fee2e2;color:#991b1b;font-size:13px;font-weight:800;line-height:1.4';root.querySelector('.inlet-form')?.prepend(box);}box.textContent=msg;}
function loadPostcode(cb){if(window.daum&&window.daum.Postcode)return cb(true);var old=document.querySelector('script[data-daum-postcode="true"]');if(old){old.addEventListener('load',function(){cb(true)},{once:true});old.addEventListener('error',function(){cb(false)},{once:true});return;}var s=document.createElement('script');s.src='https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js';s.async=true;s.dataset.daumPostcode='true';s.onload=function(){cb(true)};s.onerror=function(){cb(false)};document.head.appendChild(s);}
function field(q){var req=q.required?' required':'',ph=esc(q.placeholder||q.label||'');if(q.type==='long')return '<textarea name="'+esc(q.id)+'" placeholder="'+ph+'"'+req+'></textarea>';if(q.type==='email')return '<input type="email" inputmode="email" autocomplete="email" name="'+esc(q.id)+'" placeholder="'+ph+'"'+req+'>';if(q.type==='phone')return '<input type="tel" inputmode="tel" autocomplete="tel" name="'+esc(q.id)+'" placeholder="'+ph+'"'+req+'>';if(q.type==='name')return '<input type="text" autocomplete="name" name="'+esc(q.id)+'" placeholder="'+ph+'"'+req+'>';if(q.type==='address')return '<div class="inlet-address" data-address-id="'+esc(q.id)+'"><button type="button" data-address-button="'+esc(q.id)+'">주소 검색</button><input type="text" name="'+esc(q.id)+'_base" placeholder="'+ph+'" readonly'+req+'><input type="text" name="'+esc(q.id)+'_detail" placeholder="상세주소"><input type="hidden" name="'+esc(q.id)+'_postcode"></div>';if(q.type==='select')return '<select name="'+esc(q.id)+'"'+req+'><option value="">'+esc(q.label)+'</option>'+(q.options||[]).map(function(o){return '<option>'+esc(o)+'</option>'}).join('')+'</select>';if(q.type==='multi')return '<div class="inlet-multi"><span>'+esc(q.label)+(q.required?' *':'')+'</span>'+(q.options||[]).map(function(o){return '<label><input type="checkbox" name="'+esc(q.id)+'" value="'+esc(o)+'"> '+esc(o)+'</label>'}).join('')+'</div>';return '<input type="text" name="'+esc(q.id)+'" placeholder="'+ph+'"'+req+'>';}
root.innerHTML='<style>.inlet-form{max-width:520px;margin:0 auto;padding:24px;border:1px solid #e5e7eb;border-radius:24px;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#fff;color:#111827}.inlet-form h2{margin:0 0 8px;font-size:26px;letter-spacing:-.04em}.inlet-form p{margin:0 0 18px;color:#64748b;line-height:1.6}.inlet-form form{display:grid;gap:12px}.inlet-form input,.inlet-form textarea,.inlet-form select{width:100%;min-height:48px;border:1px solid #dbe3ef;border-radius:14px;padding:0 14px;font:inherit}.inlet-form textarea{min-height:110px;padding:13px 14px}.inlet-form button[type=submit],.inlet-address button{min-height:50px;border:0;border-radius:15px;background:#111827;color:#fff;font-weight:800;cursor:pointer}.inlet-address{display:grid;gap:8px}.inlet-multi{display:grid;gap:8px;padding:13px;border:1px solid #dbe3ef;border-radius:14px}.inlet-multi span{font-weight:800}.inlet-multi label,.inlet-agree{font-size:14px;color:#334155}.inlet-brand{margin-top:14px;text-align:center;font-size:12px;color:#94a3b8}.inlet-success{padding:24px;text-align:center;border-radius:20px;background:#f8fafc}.inlet-detail{white-space:pre-line;padding:12px;border-radius:12px;background:#f8fafc;color:#64748b;font-size:12px}</style><div class="inlet-form"><h2>'+esc(cfg.title)+'</h2><p>'+esc(cfg.desc)+'</p><form>'+(cfg.questions||[]).map(field).join('')+'<label class="inlet-agree"><input type="checkbox" '+(cfg.privacyRequired?'required':'')+'> '+esc(cfg.privacy)+'</label>'+(cfg.privacyDetail?'<details><summary>개인정보 내용 보기</summary><div class="inlet-detail">'+esc(cfg.privacyDetail)+'</div></details>':'')+'<button type="submit">'+esc(cfg.submit)+'</button></form><div class="inlet-brand">Made with '+brand+'</div></div>';
root.querySelectorAll('[data-address-button]').forEach(function(btn){btn.addEventListener('click',function(){var id=btn.getAttribute('data-address-button');loadPostcode(function(ok){if(!ok||!window.daum||!window.daum.Postcode){notice('주소검색을 불러오지 못했습니다.');return;}new window.daum.Postcode({oncomplete:function(data){var wrap=root.querySelector('[data-address-id="'+id+'"]');if(!wrap)return;var base=data.roadAddress||data.jibunAddress||'';wrap.querySelector('[name="'+id+'_base"]').value=base;wrap.querySelector('[name="'+id+'_postcode"]').value=data.zonecode||'';}}).open();});});});
root.querySelector('form').addEventListener('submit',function(e){e.preventDefault();var fd=new FormData(e.target),values={};cfg.questions.forEach(function(q){if(q.type==='multi')values[q.label]=fd.getAll(q.id);else if(q.type==='address')values[q.label]=[fd.get(q.id+'_postcode'),fd.get(q.id+'_base'),fd.get(q.id+'_detail')].filter(Boolean).join(' ');else values[q.label]=fd.get(q.id)||'';});var payload={brand:brand,type:'상담신청',title:cfg.title,values:values,createdAt:new Date().toISOString(),pageUrl:location.href};var done=function(){root.querySelector('.inlet-form').innerHTML='<div class="inlet-success"><h2>'+esc(cfg.successTitle)+'</h2><p>'+esc(cfg.success)+'</p><div class="inlet-brand">Made with '+brand+'</div></div>'};if(window.INLET_WEBHOOK_URL){fetch(window.INLET_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(done).catch(function(){notice('전송에 실패했습니다.')});}else{try{var saved=JSON.parse(localStorage.getItem('inlet_form_leads')||'[]');saved.unshift(payload);localStorage.setItem('inlet_form_leads',JSON.stringify(saved.slice(0,200)));}catch(err){}done();}});
})();
</script>
<!-- Inlet Form Embed End -->`;
}

