import { canUsePageDuplication } from '../lib/pageDuplication.js';

export function createWorkspacePanelProps({
  page,
  authUser,
  updateTheme,
  setStylePreviewTheme,
  leads,
  updatePage,
  leadsSyncing,
  leadPageMeta,
  loadMoreLeads,
  refreshServerLeads,
  setInboxFilters,
  updateIntegrations,
  saveNow,
  connectionsEditing,
  setConnectionsEditing,
  updateLead,
  deleteLead,
  retryLeadDelivery,
  retryFailedDeliveries,
  exportLeadsCsv,
  leadConflict,
  reloadLeadConflict,
  retryLeadConflict,
  setLeadConflict,
  accessMode,
  events,
  statsEventPageMeta,
  statsLeadPageMeta,
  statsPartial,
  statsMonth,
  setStatsMonth,
  statsPeriod,
  setStatsPeriod,
  serverStatsSummary,
  statsChannel,
  setStatsChannel,
  updateMeta,
  setNormalizedPage,
  duplicatePageWithUrl,
  checkCreatePageUrl,
  reset,
  updateAccountProfile,
  logout,
}) {
  return {
    stylePanelProps: {
      page,
      updateTheme,
      onPreviewThemeChange: setStylePreviewTheme,
    },
    inboxPanelProps: {
      leads,
      page,
      authUser,
      updatePage,
      syncing: leadsSyncing,
      totalLeads: leadPageMeta.total,
      hasMoreLeads: leadPageMeta.hasMore,
      loadMoreLeads,
      onReloadLeads: () => refreshServerLeads({ quiet: false }),
      onFiltersChange: setInboxFilters,
      updateIntegrations,
      onSavePage: saveNow,
      connectionsEditing,
      setConnectionsEditing,
      updateLead,
      deleteLead,
      retryLeadDelivery,
      retryFailedDeliveries,
      exportLeadsCsv,
      leadConflict,
      onReloadLeadConflict: reloadLeadConflict,
      onRetryLeadConflict: retryLeadConflict,
      onDismissLeadConflict: () => setLeadConflict(null),
      accessMode,
    },
    statsPanelProps: {
      events,
      leads,
      page,
      eventPageMeta: statsEventPageMeta,
      leadPageMeta: statsLeadPageMeta,
      statsPartial,
      month: statsMonth,
      onMonthChange: setStatsMonth,
      period: statsPeriod,
      onPeriodChange: setStatsPeriod,
      serverStats: serverStatsSummary,
      channel: statsChannel,
      onChannelChange: setStatsChannel,
      accessMode,
    },
    settingsPanelProps: {
      page,
      updatePage,
      updateMeta,
      updateIntegrations,
      setPage: setNormalizedPage,
      onSavePage: saveNow,
      onDuplicatePage: duplicatePageWithUrl,
      onCheckUrl: checkCreatePageUrl,
      canDuplicatePage: canUsePageDuplication(page, authUser),
      onReset: reset,
      authUser,
      accessMode,
      onAccountUpdate: updateAccountProfile,
      onLogout: logout,
    },
  };
}